### ISSUE TITLE
Support multiple groups

### ISSUE THREAD

**Issue by G-Rath** [G-Rath/gh-rr#1]
```yaml
repositories:
  octocat/hello-world:
    default:
      - octocat
    infra:
      - octodog
      - octopus
  octocat/hello-sunshine:
    default:
      - octodog
      - octopus
```

The `default` group is used by default, and then you can do something like `gh rr --from infra octocat/hello-world 123`
