### ISSUE TITLE
support omitting `default`

### ISSUE THREAD

**Issue by G-Rath** [G-Rath/gh-rr#13]
```
repositories:
  octocat/hello-world:
    default:
      - octocat
    infra:
      - octodog
      - octopus
  octocat/hello-sunshine:
    - octodog
    - octopus
```

should result in `octocat/hello-sunshine` having the `default` group mapped.

This will require a custom YAML parser function, and might not be worth doing but let's explore the effort first before deciding against it
