### ISSUE TITLE
handle blank values

### ISSUE THREAD

**Issue by G-Rath** [G-Rath/gh-rr#23]
```
repositories:
  octocat/hello-world:
    default:
      - !!!
      - ' '
      -
      - octopus
```

These all give blank values, which we end up passing to `gh` - we should do something about that
