### ISSUE TITLE
Support "global" repository

### ISSUE THREAD

**Issue by G-Rath** [G-Rath/gh-rr#3]
Something like

```
repositories:
  '*':
    cat: [octocat]
    dog: [octodog]
    infra:
      - octodog
      - octopus
  octocat/hello-world:
    default:
      - octocat
```

and then you could do something like `gh rr --global --from cat octocat/hello-world 123`
